language: go

go:
  - "1.15.x"
  - "1.16.x"
  - "1.17.x"

jobs:
  include:
    - arch: amd64
      os: linux
    - arch: arm64-graviton2
      virt: vm
      os: linux
      dist: focal
      group: edge

install:
  - go mod tidy
  - go mod download

script:
  - go test -v ./...
