language: go

jobs:
  include:
    - arch: arm64-graviton2
      virt: vm
      os: linux
      dist: focal
      go: 1.15.x
      group: edge

install:
  - go mod tidy
  - go mod download

script:
  - go test -v -short ./...

#after_success:
#  - go test -v -short -bench . -run=^$ ./...
