name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goVer: ['1.16', '1.17', '1.18']    
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
  
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.goVer }}
       
    - name: Test with Coverage
      run: go test -coverpkg=./... -v -short -coverprofile=coverage1.txt -covermode=atomic ./...
      env:
        GODEBUG: x509sha1=1

    - name: Test Generic
      run: go test -coverpkg=./... -v -short -tags purego  -coverprofile=coverage2.txt -covermode=atomic ./...      
      env:
        GODEBUG: x509sha1=1

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage1.txt,./coverage2.txt
