# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: test-qemu

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    strategy:
      matrix:
        go-version: [1.18.x]
        arch: [arm64]  
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Check out code
      uses: actions/checkout@v3
      
    - name: Setup Environment
      run: |
         echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
         echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

    - name: Module cache
      uses: actions/cache@v3
      env:
        cache-name: go-mod-cache
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/go.sum') }}

    - name: Test
      run: go test -v -short ./...
      env:
        DISABLE_SM3NI: 1
        DISABLE_SM4NI: 1
        GODEBUG: x509sha1=1
        GOARCH: ${{ matrix.arch }}      
